import {
  BiAddToQueue,
  BiAdjust,
  BiAlarm,
  BiAlbum,
  BiAlignJustify,
  BiAlignLeft,
  BiAlignMiddle,
  BiAlignRight,
  BiAnalyse,
  BiAperture,
  BiArchive,
  BiAtom,
  BiAward,
  BiBadgeCheck,
  BiBarChartAlt,
  BiBath,
  BiBattery,
  BiBed,
  BiBeenHere,
  BiBeer,
  BiBell,
  BiBlock,
  BiBook,
  BiBookmarkAlt,
  BiBookmarks,
  BiBox,
  BiBriefcaseAlt,
  BiBuilding,
  BiBrush,
  BiBulb,
  BiBullseye,
  BiBuoy,
  BiCake,
  BiCalculator,
  BiCalendar,
  BiCameraMovie,
  BiCamera,
  BiCapsule,
  BiCar,
  BiCart,
  BiChat,
  BiCheckCircle,
  BiCheckShield,
  BiCheck,
  BiChevronDown,
  BiCloudDownload,
  BiCloudUpload,
  BiCloud,
  BiCodeAlt,
  BiCodeCurly,
  BiCode,
  BiCoffee,
  BiCog,
  BiCoinStack,
  BiCoin,
  BiCollection,
  BiColorFill,
  BiComment,
  BiCopy,
  BiCreditCard,
  BiCrop,
  BiCube,
  BiCut,
  BiCycling,
  BiCylinder,
  BiData,
  BiDesktop,
  BiDetail,
  BiDish,
  BiDollar,
  BiDonateHeart,
  BiDownload,
  BiImport,
  BiDrink,
  BiDumbbell,
  BiDuplicate,
  BiEditAlt,
  BiEnvelope,
  BiError,
  BiExport,
  BiExtension,
  BiFileBlank,
  BiFilterAlt,
  BiFlag,
  BiFolder,
  BiFont,
  BiGame,
  BiGasPump,
  BiGhost,
  BiGift,
  BiGitBranch,
  BiGlasses,
  BiGlobe,
  BiHappy,
  BiHdd,
  BiHeadphone,
  BiHeart,
  BiHourglass,
  BiImage,
  BiImages,
  BiInfinite,
  BiLandscape,
  BiLayer,
  BiLinkAlt,
  BiLock,
  BiMagnet,
  BiMailSend,
  BiMapAlt,
  BiMapPin,
  BiMedal,
  BiMessage,
  BiMeteor,
  BiMicrophone,
  BiMoon,
  BiMouse,
  BiMovie,
  BiMusic,
  BiNotification,
  BiPaint,
  BiPalette,
  BiPaperPlane,
  BiPen,
  BiPencil,
  BiPhone,
  BiPlanet,
  BiPlug,
  BiPointer,
  BiPowerOff,
  BiPulse,
  BiRadio,
  BiReceipt,
  BiRocket,
  BiRuler,
  BiSave,
  BiSearchAlt,
  BiServer,
  BiShield,
  BiShoppingBag,
  BiShow,
  BiSitemap,
  BiSliderAlt,
  BiSort,
  BiSpa,
  BiStar,
  BiStore,
  BiSun,
  BiTag,
  BiTestTube,
  BiText,
  BiTime,
  BiTrashAlt,
  BiTrendingDown,
  BiTrendingUp,
  BiTrophy,
  BiUser,
  BiGroup,
  BiVolume,
  BiWallet,
  BiWifi,
  BiWindowAlt,
  BiWrench,
  BiX,
  BiZoomIn,
  BiZoomOut,
} from "react-icons/bi";

export const Icon = ({ id, variant, dropdownStyle, renderStyle }) => {
  const iconList = [
    {
      id: "a2r83FDS79w1jjTgsgTNGA",
      name: "Add To Queue",
      component: <BiAddToQueue className={dropdownStyle} />,
      render: <BiAddToQueue className={renderStyle} />,
    },
    {
      id: "fCF4jVhDKs2wYbtGqCY4tY",
      name: "Adjust",
      component: <BiAdjust className={dropdownStyle} />,
      render: <BiAdjust className={renderStyle} />,
    },
    {
      id: "6bkzp45PiP34LTSXpZg6Ws",
      name: "Alarm",
      component: <BiAlarm className={dropdownStyle} />,
      render: <BiAlarm className={renderStyle} />,
    },
    {
      id: "ncYcJ4qTMtW3efjLtVeVBG",
      name: "Album",
      component: <BiAlbum className={dropdownStyle} />,
      render: <BiAlbum className={renderStyle} />,
    },
    {
      id: "9xEYkP9rb7HgyQKQ7i8UTE",
      name: "Align Justify",
      component: <BiAlignJustify className={dropdownStyle} />,
      render: <BiAlignJustify className={renderStyle} />,
    },
    {
      id: "bdccDZVrDV6kTRkgFX6Czo",
      name: "Align Left",
      component: <BiAlignLeft className={dropdownStyle} />,
      render: <BiAlignLeft className={renderStyle} />,
    },
    {
      id: "2JTYCsfRsttYAugTahwdD7",
      name: "Align Middle",
      component: <BiAlignMiddle className={dropdownStyle} />,
      render: <BiAlignMiddle className={renderStyle} />,
    },
    {
      id: "x9WWUucJqWdAGxxsGkiSuf",
      name: "Align Right",
      component: <BiAlignRight className={dropdownStyle} />,
      render: <BiAlignRight className={renderStyle} />,
    },
    {
      id: "cw9wsWARgerG9zzHFzxv3S",
      name: "Analyse",
      component: <BiAnalyse className={dropdownStyle} />,
      render: <BiAnalyse className={renderStyle} />,
    },
    {
      id: "qEqRid9mcCnsdS9TEz9BTs",
      name: "Aperture",
      component: <BiAperture className={dropdownStyle} />,
      render: <BiAperture className={renderStyle} />,
    },
    {
      id: "3u6WdDmmje6f38GDnokjfP",
      name: "Archive",
      component: <BiArchive className={dropdownStyle} />,
      render: <BiArchive className={renderStyle} />,
    },
    {
      id: "h1KRhpRPPZR1hhmaU1spoH",
      name: "Atom",
      component: <BiAtom className={dropdownStyle} />,
      render: <BiAtom className={renderStyle} />,
    },
    {
      id: "1Uc2MS1uzCv1XH6zwRDzTt",
      name: "Award",
      component: <BiAward className={dropdownStyle} />,
      render: <BiAward className={renderStyle} />,
    },
    {
      id: "7GdcEc9yhi1cKK4dfJKzYe",
      name: "Badge Check",
      component: <BiBadgeCheck className={dropdownStyle} />,
      render: <BiBadgeCheck className={renderStyle} />,
    },
    {
      id: "ePMUkivKMV5w3sxKkWxQhL",
      name: "Bar Chart Alt",
      component: <BiBarChartAlt className={dropdownStyle} />,
      render: <BiBarChartAlt className={renderStyle} />,
    },
    {
      id: "xi7RYuUM187g5mppS3db53",
      name: "Bath",
      component: <BiBath className={dropdownStyle} />,
      render: <BiBath className={renderStyle} />,
    },
    {
      id: "75ecKiYdX6x9KSAdNCej2f",
      name: "Battery",
      component: <BiBattery className={dropdownStyle} />,
      render: <BiBattery className={renderStyle} />,
    },
    {
      id: "qwvrmwB91F7uGhUxoSQHtn",
      name: "Bed",
      component: <BiBed className={dropdownStyle} />,
      render: <BiBed className={renderStyle} />,
    },
    {
      id: "3M5W7cm7K6pPgvaPfThSoj",
      name: "Been Here",
      component: <BiBeenHere className={dropdownStyle} />,
      render: <BiBeenHere className={renderStyle} />,
    },
    {
      id: "fYTUCdA53TfLtb5L27ghSt",
      name: "Beer",
      component: <BiBeer className={dropdownStyle} />,
      render: <BiBeer className={renderStyle} />,
    },
    {
      id: "s4tCggwuZsXxq2kZUHAsyF",
      name: "Bell",
      component: <BiBell className={dropdownStyle} />,
      render: <BiBell className={renderStyle} />,
    },
    {
      id: "uB9F6tTQQgMpcT9J6CgoQU",
      name: "Block",
      component: <BiBlock className={dropdownStyle} />,
      render: <BiBlock className={renderStyle} />,
    },
    {
      id: "4yLumaeRPU2dNbzkHNgo6t",
      name: "Book",
      component: <BiBook className={dropdownStyle} />,
      render: <BiBook className={renderStyle} />,
    },
    {
      id: "1xreCDYK8wn2UgYYAg5Uny",
      name: "Bookmark Alt",
      component: <BiBookmarkAlt className={dropdownStyle} />,
      render: <BiBookmarkAlt className={renderStyle} />,
    },
    {
      id: "2B7SkHccAzvsKR5MvLTX41",
      name: "Bookmarks",
      component: <BiBookmarks className={dropdownStyle} />,
      render: <BiBookmarks className={renderStyle} />,
    },
    {
      id: "nor3PJU2D4C4HEGKNy97nS",
      name: "Box",
      component: <BiBox className={dropdownStyle} />,
      render: <BiBox className={renderStyle} />,
    },
    {
      id: "6kkLYEK5abNo6BAWwPHzNV",
      name: "Briefcase Alt",
      component: <BiBriefcaseAlt className={dropdownStyle} />,
      render: <BiBriefcaseAlt className={renderStyle} />,
    },
    {
      id: "uqz2cKD4FKmBxEHTe7V9vi",
      name: "Building",
      component: <BiBuilding className={dropdownStyle} />,
      render: <BiBuilding className={renderStyle} />,
    },
    {
      id: "evpGuTnkU1UGM3TKr6JxcA",
      name: "Brush",
      component: <BiBrush className={dropdownStyle} />,
      render: <BiBrush className={renderStyle} />,
    },
    {
      id: "wUYqDC6Q6JZMqwZn6opH93",
      name: "Bulb",
      component: <BiBulb className={dropdownStyle} />,
      render: <BiBulb className={renderStyle} />,
    },
    {
      id: "uTijmPmGupesfzEBmqYNnP",
      name: "Bullseye",
      component: <BiBullseye className={dropdownStyle} />,
      render: <BiBullseye className={renderStyle} />,
    },
    {
      id: "9d5YZSDzDGwRPzn85Le18e",
      name: "Buoy",
      component: <BiBuoy className={dropdownStyle} />,
      render: <BiBuoy className={renderStyle} />,
    },
    {
      id: "5zTyz3su1B4izo4oikDVAZ",
      name: "Cake",
      component: <BiCake className={dropdownStyle} />,
      render: <BiCake className={renderStyle} />,
    },
    {
      id: "g15bfpqmEnkcmUfeLLHCFK",
      name: "Calculator",
      component: <BiCalculator className={dropdownStyle} />,
      render: <BiCalculator className={renderStyle} />,
    },
    {
      id: "htLXy1rFA2KruHqqWjGbWt",
      name: "Calendar",
      component: <BiCalendar className={dropdownStyle} />,
      render: <BiCalendar className={renderStyle} />,
    },
    {
      id: "uHh7Boj6Ca9ibKJkb8A1TX",
      name: "Camera Movie",
      component: <BiCameraMovie className={dropdownStyle} />,
      render: <BiCameraMovie className={renderStyle} />,
    },
    {
      id: "aLmKF3xZvWTrFieeZDs8y9",
      name: "Camera",
      component: <BiCamera className={dropdownStyle} />,
      render: <BiCamera className={renderStyle} />,
    },
    {
      id: "2Q6jYj2j39FR6zyhoRDh2o",
      name: "Capsule",
      component: <BiCapsule className={dropdownStyle} />,
      render: <BiCapsule className={renderStyle} />,
    },
    {
      id: "gvx1pAjr73ZhxW5vSf82zE",
      name: "Car",
      component: <BiCar className={dropdownStyle} />,
      render: <BiCar className={renderStyle} />,
    },
    {
      id: "8nKyvHL2rd472y2P6VHtiY",
      name: "Cart",
      component: <BiCart className={dropdownStyle} />,
      render: <BiCart className={renderStyle} />,
    },
    {
      id: "47T1r1eT1bDozwuSZe3Nt7",
      name: "Chat",
      component: <BiChat className={dropdownStyle} />,
      render: <BiChat className={renderStyle} />,
    },
    {
      id: "o2DvARVuRLhg4fnUSiCJv6",
      name: "Check Circle",
      component: <BiCheckCircle className={dropdownStyle} />,
      render: <BiCheckCircle className={renderStyle} />,
    },
    {
      id: "tsh6XW1LQyZAn42aGbv1ag",
      name: "Check Shield",
      component: <BiCheckShield className={dropdownStyle} />,
      render: <BiCheckShield className={renderStyle} />,
    },
    {
      id: "a2J7es89Pfi8txQbJkN5YL",
      name: "Check",
      component: <BiCheck className={dropdownStyle} />,
      render: <BiCheck className={renderStyle} />,
    },
    {
      id: "1vsssau5Kdz5Fs9Ubte6W3",
      name: "Chevron Down",
      component: <BiChevronDown className={dropdownStyle} />,
      render: <BiChevronDown className={renderStyle} />,
    },
    {
      id: "2cxdfeAswm2QBg4p8eJcT8",
      name: "Cloud Download",
      component: <BiCloudDownload className={dropdownStyle} />,
      render: <BiCloudDownload className={renderStyle} />,
    },
    {
      id: "9LDqeVq2m5k9cTBm2m8xvq",
      name: "Cloud Upload",
      component: <BiCloudUpload className={dropdownStyle} />,
      render: <BiCloudUpload className={renderStyle} />,
    },
    {
      id: "qXLiTdZyR995VKQmgXquuU",
      name: "Cloud",
      component: <BiCloud className={dropdownStyle} />,
      render: <BiCloud className={renderStyle} />,
    },
    {
      id: "1uXzfZDvnmfr4pPKbQoYmn",
      name: "Code Alt",
      component: <BiCodeAlt className={dropdownStyle} />,
      render: <BiCodeAlt className={renderStyle} />,
    },
    {
      id: "kibj5GifdJKieWrUC1hKnW",
      name: "Code Curly",
      component: <BiCodeCurly className={dropdownStyle} />,
      render: <BiCodeCurly className={renderStyle} />,
    },
    {
      id: "6nrKZksKPPsfbC74GnNaeV",
      name: "Code",
      component: <BiCode className={dropdownStyle} />,
      render: <BiCode className={renderStyle} />,
    },
    {
      id: "3NNefTw3FMzFDBm9DPcAxp",
      name: "Coffee",
      component: <BiCoffee className={dropdownStyle} />,
      render: <BiCoffee className={renderStyle} />,
    },
    {
      id: "5ykAtPQNrtjyTZedSddhpq",
      name: "Cog",
      component: <BiCog className={dropdownStyle} />,
      render: <BiCog className={renderStyle} />,
    },
    {
      id: "jYUxc8Uxr44nDjQ9BRWpw7",
      name: "Coin Stack",
      component: <BiCoinStack className={dropdownStyle} />,
      render: <BiCoinStack className={renderStyle} />,
    },
    {
      id: "evSr6EMURyiMwgDU9MWeV2",
      name: "Coin",
      component: <BiCoin className={dropdownStyle} />,
      render: <BiCoin className={renderStyle} />,
    },
    {
      id: "fEMdijYS111KXcQVu2CVWG",
      name: "Collection",
      component: <BiCollection className={dropdownStyle} />,
      render: <BiCollection className={renderStyle} />,
    },
    {
      id: "gV3CKJq45sYQCPDfqc9RQv",
      name: "Color Fill",
      component: <BiColorFill className={dropdownStyle} />,
      render: <BiColorFill className={renderStyle} />,
    },
    {
      id: "prYb81SYY6LqhfCjrDp2RU",
      name: "Comment",
      component: <BiComment className={dropdownStyle} />,
      render: <BiComment className={renderStyle} />,
    },
    {
      id: "pAjM2jns9CxikTKMnjbdEs",
      name: "Copy",
      component: <BiCopy className={dropdownStyle} />,
      render: <BiCopy className={renderStyle} />,
    },
    {
      id: "iPdCVq9SjrQEp4Eea4pKJW",
      name: "Credit Card",
      component: <BiCreditCard className={dropdownStyle} />,
      render: <BiCreditCard className={renderStyle} />,
    },
    {
      id: "idiF1qs2VNYgX5rVfa4coz",
      name: "Crop",
      component: <BiCrop className={dropdownStyle} />,
      render: <BiCrop className={renderStyle} />,
    },
    {
      id: "sCXHL3Ta63TRC6M5TcPPbS",
      name: "Cube",
      component: <BiCube className={dropdownStyle} />,
      render: <BiCube className={renderStyle} />,
    },
    {
      id: "7gopPJRZYP3LYZduHXTmfe",
      name: "Cut",
      component: <BiCut className={dropdownStyle} />,
      render: <BiCut className={renderStyle} />,
    },
    {
      id: "h12DsgHvaHHRU3LkJ8Cyeb",
      name: "Cycling",
      component: <BiCycling className={dropdownStyle} />,
      render: <BiCycling className={renderStyle} />,
    },
    {
      id: "tso56wQGt8dSfcsoAUkm7k",
      name: "Cylinder",
      component: <BiCylinder className={dropdownStyle} />,
      render: <BiCylinder className={renderStyle} />,
    },
    {
      id: "v5iM7jtBgMjHy3QcmHNy9F",
      name: "Data",
      component: <BiData className={dropdownStyle} />,
      render: <BiData className={renderStyle} />,
    },
    {
      id: "bVekCoaSsnKUNy88ESKUub",
      name: "Desktop",
      component: <BiDesktop className={dropdownStyle} />,
      render: <BiDesktop className={renderStyle} />,
    },
    {
      id: "sb4dLhyVsTh7x8Fzx4Mjfc",
      name: "Detail",
      component: <BiDetail className={dropdownStyle} />,
      render: <BiDetail className={renderStyle} />,
    },
    {
      id: "5tiT6sU1QhUzXTctTnFZ9x",
      name: "Dish",
      component: <BiDish className={dropdownStyle} />,
      render: <BiDish className={renderStyle} />,
    },
    {
      id: "syYYTd1rUU7e1wZpgDMRdS",
      name: "Dollar",
      component: <BiDollar className={dropdownStyle} />,
      render: <BiDollar className={renderStyle} />,
    },
    {
      id: "ok4EWwdFLgFbGP7AqQt2PD",
      name: "Donate Heart",
      component: <BiDonateHeart className={dropdownStyle} />,
      render: <BiDonateHeart className={renderStyle} />,
    },
    {
      id: "8dParqYWNmeijvBgK8UhyX",
      name: "Download",
      component: <BiDownload className={dropdownStyle} />,
      render: <BiDownload className={renderStyle} />,
    },
    {
      id: "bMyTcfvVLTsZ29emP7BQCN",
      name: "Import",
      component: <BiImport className={dropdownStyle} />,
      render: <BiImport className={renderStyle} />,
    },
    {
      id: "e6tQaSxo1BXL93xwKWw1hT",
      name: "Drink",
      component: <BiDrink className={dropdownStyle} />,
      render: <BiDrink className={renderStyle} />,
    },
    {
      id: "xyxBPJDKRoPfyzyhexv3zp",
      name: "Dumbbell",
      component: <BiDumbbell className={dropdownStyle} />,
      render: <BiDumbbell className={renderStyle} />,
    },
    {
      id: "uqi3Aw7Uw9DC4UKbuoFXn2",
      name: "Duplicate",
      component: <BiDuplicate className={dropdownStyle} />,
      render: <BiDuplicate className={renderStyle} />,
    },
    {
      id: "2mbuahVTSfaUw73g5ND3bd",
      name: "Edit Alt",
      component: <BiEditAlt className={dropdownStyle} />,
      render: <BiEditAlt className={renderStyle} />,
    },
    {
      id: "k6riDR69bohk6XQ7M1Ry5n",
      name: "Envelope",
      component: <BiEnvelope className={dropdownStyle} />,
      render: <BiEnvelope className={renderStyle} />,
    },
    {
      id: "m1o5CeyNrQz83c7U9Ayf91",
      name: "Error",
      component: <BiError className={dropdownStyle} />,
      render: <BiError className={renderStyle} />,
    },
    {
      id: "gaSPD1NWoNJEPWt2qCw3dU",
      name: "Export",
      component: <BiExport className={dropdownStyle} />,
      render: <BiExport className={renderStyle} />,
    },
    {
      id: "cEs226quQZ4kfAosqrG6Jh",
      name: "Extension",
      component: <BiExtension className={dropdownStyle} />,
      render: <BiExtension className={renderStyle} />,
    },
    {
      id: "rQx9Hs3pJs9HjxcLGpY1Vp",
      name: "File Blank",
      component: <BiFileBlank className={dropdownStyle} />,
      render: <BiFileBlank className={renderStyle} />,
    },
    {
      id: "gqVnkRqacUwd3w3R4u4DpF",
      name: "Filter Alt",
      component: <BiFilterAlt className={dropdownStyle} />,
      render: <BiFilterAlt className={renderStyle} />,
    },
    {
      id: "vLPoq4jkoTovZEaFs9VdJX",
      name: "Flag",
      component: <BiFlag className={dropdownStyle} />,
      render: <BiFlag className={renderStyle} />,
    },
    {
      id: "denUu341mmckCTrk67AzpM",
      name: "Folder",
      component: <BiFolder className={dropdownStyle} />,
      render: <BiFolder className={renderStyle} />,
    },
    {
      id: "dXu49SZpZGqufxhJsa8hAU",
      name: "Font",
      component: <BiFont className={dropdownStyle} />,
      render: <BiFont className={renderStyle} />,
    },
    {
      id: "3RU5gf4VHVZJBdM57Z3YVr",
      name: "Game",
      component: <BiGame className={dropdownStyle} />,
      render: <BiGame className={renderStyle} />,
    },
    {
      id: "b5XVoMXcdM8hoTZ8Dqscf2",
      name: "Gas Pump",
      component: <BiGasPump className={dropdownStyle} />,
      render: <BiGasPump className={renderStyle} />,
    },
    {
      id: "sUi2e1C3hfDGTGrqKcK9jF",
      name: "Ghost",
      component: <BiGhost className={dropdownStyle} />,
      render: <BiGhost className={renderStyle} />,
    },
    {
      id: "6RKzz2U16ZabCfqUtkUUbV",
      name: "Gift",
      component: <BiGift className={dropdownStyle} />,
      render: <BiGift className={renderStyle} />,
    },
    {
      id: "2yfUwkEbdsxtpzxQ7m8YZN",
      name: "Git Branch",
      component: <BiGitBranch className={dropdownStyle} />,
      render: <BiGitBranch className={renderStyle} />,
    },
    {
      id: "o9z8BEZxo2QCT8S5ZNxsjL",
      name: "Glasses",
      component: <BiGlasses className={dropdownStyle} />,
      render: <BiGlasses className={renderStyle} />,
    },
    {
      id: "5f6JjbH5uq6paaTmxsiwXA",
      name: "Globe",
      component: <BiGlobe className={dropdownStyle} />,
      render: <BiGlobe className={renderStyle} />,
    },
    {
      id: "apG3HKhwciK1C3DkSkaf76",
      name: "Happy",
      component: <BiHappy className={dropdownStyle} />,
      render: <BiHappy className={renderStyle} />,
    },
    {
      id: "wxkXhyEyurGhKy5WD74rc4",
      name: "Hdd",
      component: <BiHdd className={dropdownStyle} />,
      render: <BiHdd className={renderStyle} />,
    },
    {
      id: "b6H1f3exy8AxuazGCkc43m",
      name: "Headphone",
      component: <BiHeadphone className={dropdownStyle} />,
      render: <BiHeadphone className={renderStyle} />,
    },
    {
      id: "rXkyQQtdWELpygcYjn75Yb",
      name: "Heart",
      component: <BiHeart className={dropdownStyle} />,
      render: <BiHeart className={renderStyle} />,
    },
    {
      id: "8w33LZaSMTS9AbZXZK2GNX",
      name: "Hourglass",
      component: <BiHourglass className={dropdownStyle} />,
      render: <BiHourglass className={renderStyle} />,
    },
    {
      id: "myERgEGPgbFVXUsFKroJuH",
      name: "Image",
      component: <BiImage className={dropdownStyle} />,
      render: <BiImage className={renderStyle} />,
    },
    {
      id: "n7ZV32k1V8xDt5PmuViLpw",
      name: "Images",
      component: <BiImages className={dropdownStyle} />,
      render: <BiImages className={renderStyle} />,
    },
    {
      id: "2Qe74FjHpWTePcyhpzUtzX",
      name: "Infinite",
      component: <BiInfinite className={dropdownStyle} />,
      render: <BiInfinite className={renderStyle} />,
    },
    {
      id: "dqYrd5NjwWkYRXGiYTdqtm",
      name: "Landscape",
      component: <BiLandscape className={dropdownStyle} />,
      render: <BiLandscape className={renderStyle} />,
    },
    {
      id: "auJW5wWN72HaYvg6YyYyNk",
      name: "Layer",
      component: <BiLayer className={dropdownStyle} />,
      render: <BiLayer className={renderStyle} />,
    },
    {
      id: "biou2LvQzWiAPZCVYwfo5U",
      name: "Link Alt",
      component: <BiLinkAlt className={dropdownStyle} />,
      render: <BiLinkAlt className={renderStyle} />,
    },
    {
      id: "2NczBLJPvy6hT6p8Jgr56D",
      name: "Lock",
      component: <BiLock className={dropdownStyle} />,
      render: <BiLock className={renderStyle} />,
    },
    {
      id: "hSejtp4HoH9MWWKTaznbPF",
      name: "Magnet",
      component: <BiMagnet className={dropdownStyle} />,
      render: <BiMagnet className={renderStyle} />,
    },
    {
      id: "7tBFgZKJYb862wAnrByswk",
      name: "Mail Send",
      component: <BiMailSend className={dropdownStyle} />,
      render: <BiMailSend className={renderStyle} />,
    },
    {
      id: "oTx8G2o3SoLtYjEfWvJxJp",
      name: "Map Alt",
      component: <BiMapAlt className={dropdownStyle} />,
      render: <BiMapAlt className={renderStyle} />,
    },
    {
      id: "rVyBrwcmCBnLfySyablueXH",
      name: "Map Pin",
      component: <BiMapPin className={dropdownStyle} />,
      render: <BiMapPin className={renderStyle} />,
    },
    {
      id: "64QUiZvL9YhBNDTwKMJjDC",
      name: "Medal",
      component: <BiMedal className={dropdownStyle} />,
      render: <BiMedal className={renderStyle} />,
    },
    {
      id: "oubxUKZat1ynsN5KQjBZqj",
      name: "Message",
      component: <BiMessage className={dropdownStyle} />,
      render: <BiMessage className={renderStyle} />,
    },
    {
      id: "5B7UeLgW3AZfpod9Fkrwkd",
      name: "Meteor",
      component: <BiMeteor className={dropdownStyle} />,
      render: <BiMeteor className={renderStyle} />,
    },
    {
      id: "1cv15MFppiuj1WYmMkPWLN",
      name: "Microphone",
      component: <BiMicrophone className={dropdownStyle} />,
      render: <BiMicrophone className={renderStyle} />,
    },
    {
      id: "wBryKuEnDqavW7TP3EzFWX",
      name: "Moon",
      component: <BiMoon className={dropdownStyle} />,
      render: <BiMoon className={renderStyle} />,
    },
    {
      id: "5U4qVTZeN1P5u1BeDyd8xy",
      name: "Mouse",
      component: <BiMouse className={dropdownStyle} />,
      render: <BiMouse className={renderStyle} />,
    },
    {
      id: "bUyLn9J65tgKYEtjU3t4uZ",
      name: "Movie",
      component: <BiMovie className={dropdownStyle} />,
      render: <BiMovie className={renderStyle} />,
    },
    {
      id: "jrFNf5K7dcMMFD696gouds",
      name: "Music",
      component: <BiMusic className={dropdownStyle} />,
      render: <BiMusic className={renderStyle} />,
    },
    {
      id: "friTr1zgaALbd6JuCd8d4w",
      name: "Notification",
      component: <BiNotification className={dropdownStyle} />,
      render: <BiNotification className={renderStyle} />,
    },
    {
      id: "8kdYYRJBdjrYKNmnXsUVSy",
      name: "Paint",
      component: <BiPaint className={dropdownStyle} />,
      render: <BiPaint className={renderStyle} />,
    },
    {
      id: "sj4pZAzEgQv3DMGxKHDfFf",
      name: "Palette",
      component: <BiPalette className={dropdownStyle} />,
      render: <BiPalette className={renderStyle} />,
    },
    {
      id: "gR5Ys7XhZNJDRSiGFYZ7K2",
      name: "Paper Plane",
      component: <BiPaperPlane className={dropdownStyle} />,
      render: <BiPaperPlane className={renderStyle} />,
    },
    {
      id: "shq5h9nhaRaaarJY2kfaL1",
      name: "Pen",
      component: <BiPen className={dropdownStyle} />,
      render: <BiPen className={renderStyle} />,
    },
    {
      id: "6YNDkX8ecSqnqnTr1P3Ley",
      name: "Pencil",
      component: <BiPencil className={dropdownStyle} />,
      render: <BiPencil className={renderStyle} />,
    },
    {
      id: "kcGesti3w28szT2bFMpzoT",
      name: "Phone",
      component: <BiPhone className={dropdownStyle} />,
      render: <BiPhone className={renderStyle} />,
    },
    {
      id: "s2YHbx2wG6VcBzPSESLwH6",
      name: "Planet",
      component: <BiPlanet className={dropdownStyle} />,
      render: <BiPlanet className={renderStyle} />,
    },
    {
      id: "rLbPipfuQWdFN8TqVvtZJJ",
      name: "Plug",
      component: <BiPlug className={dropdownStyle} />,
      render: <BiPlug className={renderStyle} />,
    },
    {
      id: "rSaL3LHiAAoSJBDd8ptNjK",
      name: "Pointer",
      component: <BiPointer className={dropdownStyle} />,
      render: <BiPointer className={renderStyle} />,
    },
    {
      id: "jXk5AakgNSW73feYozCQ7g",
      name: "Power Off",
      component: <BiPowerOff className={dropdownStyle} />,
      render: <BiPowerOff className={renderStyle} />,
    },
    {
      id: "wGwLjV2BxXomCx5oRYkioo",
      name: "Pulse",
      component: <BiPulse className={dropdownStyle} />,
      render: <BiPulse className={renderStyle} />,
    },
    {
      id: "4gHMC1qGeXTt3ZTDSFSdhc",
      name: "Radio",
      component: <BiRadio className={dropdownStyle} />,
      render: <BiRadio className={renderStyle} />,
    },
    {
      id: "3eWHs9CFbB4Ub8Nva1y3Cx",
      name: "Receipt",
      component: <BiReceipt className={dropdownStyle} />,
      render: <BiReceipt className={renderStyle} />,
    },
    {
      id: "7btyuD5XwLV7pt957S3HGb",
      name: "Rocket",
      component: <BiRocket className={dropdownStyle} />,
      render: <BiRocket className={renderStyle} />,
    },
    {
      id: "5FaqBbNpzi78u8JiFVtbq1",
      name: "Ruler",
      component: <BiRuler className={dropdownStyle} />,
      render: <BiRuler className={renderStyle} />,
    },
    {
      id: "wuETe2Q8SqbtHLBUaz2jeZ",
      name: "Save",
      component: <BiSave className={dropdownStyle} />,
      render: <BiSave className={renderStyle} />,
    },
    {
      id: "nCcCAakjb8sc1B71comJ6C",
      name: "Search Alt",
      component: <BiSearchAlt className={dropdownStyle} />,
      render: <BiSearchAlt className={renderStyle} />,
    },
    {
      id: "bwYYRXdvWoFFHJMyvmmt9x",
      name: "Server",
      component: <BiServer className={dropdownStyle} />,
      render: <BiServer className={renderStyle} />,
    },
    {
      id: "t7vhmXMhAsCanLquyg6X8X",
      name: "Shield",
      component: <BiShield className={dropdownStyle} />,
      render: <BiShield className={renderStyle} />,
    },
    {
      id: "8NRzHQoQXxa9TDP4Wjgd9H",
      name: "Shopping Bag",
      component: <BiShoppingBag className={dropdownStyle} />,
      render: <BiShoppingBag className={renderStyle} />,
    },
    {
      id: "mZ4LFtEezKiNRMxvn3qWVv",
      name: "Show",
      component: <BiShow className={dropdownStyle} />,
      render: <BiShow className={renderStyle} />,
    },
    {
      id: "akn7rP4mXLA9RvG1XACvCU",
      name: "Sitemap",
      component: <BiSitemap className={dropdownStyle} />,
      render: <BiSitemap className={renderStyle} />,
    },
    {
      id: "8C8jNSFuhi8BiwksreQcba",
      name: "Slider Alt",
      component: <BiSliderAlt className={dropdownStyle} />,
      render: <BiSliderAlt className={renderStyle} />,
    },
    {
      id: "dXwGuuzQsYEzUPMPE5tBWL",
      name: "Sort",
      component: <BiSort className={dropdownStyle} />,
      render: <BiSort className={renderStyle} />,
    },
    {
      id: "7vGdTdNLf6T2acGwZedqnX",
      name: "Spa",
      component: <BiSpa className={dropdownStyle} />,
      render: <BiSpa className={renderStyle} />,
    },
    {
      id: "9QZSLxC5rapoaEAdZacbL6",
      name: "Star",
      component: <BiStar className={dropdownStyle} />,
      render: <BiStar className={renderStyle} />,
    },
    {
      id: "4PnskqyM3R3W4nE29DyuxU",
      name: "Store",
      component: <BiStore className={dropdownStyle} />,
      render: <BiStore className={renderStyle} />,
    },
    {
      id: "2ozkhNkiXe88j9zRVvzg5w",
      name: "Sun",
      component: <BiSun className={dropdownStyle} />,
      render: <BiSun className={renderStyle} />,
    },
    {
      id: "xeZ5spWLqhep6HPqXk95fW",
      name: "Tag",
      component: <BiTag className={dropdownStyle} />,
      render: <BiTag className={renderStyle} />,
    },
    {
      id: "wZHKRA15fyFF1iGiG7bDPA",
      name: "Test Tube",
      component: <BiTestTube className={dropdownStyle} />,
      render: <BiTestTube className={renderStyle} />,
    },
    {
      id: "9Wj82PKKjKsjgSLoW9dzX8",
      name: "Text",
      component: <BiText className={dropdownStyle} />,
      render: <BiText className={renderStyle} />,
    },
    {
      id: "rNpSsDMjAjdnUtctW5tCmA",
      name: "Time",
      component: <BiTime className={dropdownStyle} />,
      render: <BiTime className={renderStyle} />,
    },
    {
      id: "euWAkDd1VfQEi6xYWBSpaE",
      name: "Trash Alt",
      component: <BiTrashAlt className={dropdownStyle} />,
      render: <BiTrashAlt className={renderStyle} />,
    },
    {
      id: "3PQEG5ihvejMbqdFc1fpY7",
      name: "Trending Down",
      component: <BiTrendingDown className={dropdownStyle} />,
      render: <BiTrendingDown className={renderStyle} />,
    },
    {
      id: "kyX4DuS6seXWyhLPST8NqR",
      name: "Trending Up",
      component: <BiTrendingUp className={dropdownStyle} />,
      render: <BiTrendingUp className={renderStyle} />,
    },
    {
      id: "iyfem2oDdH4exdxaJVw1MD",
      name: "Trophy",
      component: <BiTrophy className={dropdownStyle} />,
      render: <BiTrophy className={renderStyle} />,
    },
    {
      id: "c2jXCcTDVEvfcKS4sYreTe",
      name: "User",
      component: <BiUser className={dropdownStyle} />,
      render: <BiUser className={renderStyle} />,
    },
    {
      id: "1spUQ1q2oaqR1wFkKhX96d",
      name: "Group",
      component: <BiGroup className={dropdownStyle} />,
      render: <BiGroup className={renderStyle} />,
    },
    {
      id: "3aZT8ZTPj31xB5PmZGEBwv",
      name: "Volume",
      component: <BiVolume className={dropdownStyle} />,
      render: <BiVolume className={renderStyle} />,
    },
    {
      id: "pQxa676cD5JnUpMwMuJt9E",
      name: "Wallet",
      component: <BiWallet className={dropdownStyle} />,
      render: <BiWallet className={renderStyle} />,
    },
    {
      id: "9pRakq3VMfCEbVZwkiG2Rx",
      name: "Wifi",
      component: <BiWifi className={dropdownStyle} />,
      render: <BiWifi className={renderStyle} />,
    },
    {
      id: "wqmWaXsuEtHF97fQT6BP3E",
      name: "Window Alt",
      component: <BiWindowAlt className={dropdownStyle} />,
      render: <BiWindowAlt className={renderStyle} />,
    },
    {
      id: "s1wUdEYLLygxfSpkCspoYn",
      name: "Wrench",
      component: <BiWrench className={dropdownStyle} />,
      render: <BiWrench className={renderStyle} />,
    },
    {
      id: "9DterPR5BP49gHtftNCwNM",
      name: "X",
      component: <BiX className={dropdownStyle} />,
      render: <BiX className={renderStyle} />,
    },
    {
      id: "otZmqj6AdyHwP6nM7FDQBA",
      name: "Zoom In",
      component: <BiZoomIn className={dropdownStyle} />,
      render: <BiZoomIn className={renderStyle} />,
    },
    {
      id: "eKk1eJMB4HbqNZ5Y9mYQMR",
      name: "Zoom Out",
      component: <BiZoomOut className={dropdownStyle} />,
      render: <BiZoomOut className={renderStyle} />,
    },
  ];

  const renderIcon = (id) => {
    switch (variant) {
      case "render":
        return iconList.find((icon) => icon.id === id).render;
      case "dropdown":
        return iconList.find((icon) => icon.id === id).component;
      default:
        return iconList.find((icon) => icon.id === id).render;
    }
  };

  return renderIcon(id);
};

Icon.defaultProps = {
  id: "a2r83FDS79w1jjTgsgTNGA",
  variant: "render",
  dropdownStyle: "w-5 h-5 text-gray-900",
  renderStyle: "w-5 h-5 text-white",
};
